/*
 * To change this template, choose Tools | Templates 
 * and open the template in the editor.
 */

/*
 * panel1.java
 *
 * Created on 9 Nov, 2012, 11:13:09 PM
 */
package GUIPackage;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class SelectInfoPanel extends javax.swing.JPanel {

    /** Creates new form panel1 */
    public SelectInfoPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtImage = new javax.swing.JTextField();
        jBtnBrowse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();

        setAlignmentX(CENTER_ALIGNMENT);
        setAlignmentY(CENTER_ALIGNMENT);

        jLabel1.setText("IMAGE");

        jtxtImage.setColumns(40);
        jtxtImage.setEnabled(false);

        jBtnBrowse.setText("BROWSE");
        jBtnBrowse.setEnabled(false);
        jBtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBrowseActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter TEXT");

        jtxtText.setColumns(20);
        jtxtText.setEnabled(false);

        jLabel3.setText("ENCRYPT");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Text", "Image" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnBrowse))
                    .addComponent(jtxtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBrowse)
                    .addComponent(jLabel1))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String[] getUserInput()
    {
      String[] streturn= new String[2];
        
      String select = (String)jComboBox.getSelectedItem();
      if(select.equals("Text"))
      {
          streturn[0]="text"; streturn[1]= jtxtText.getText();
          return streturn;
      }
      if(select.equals("Image"))
      {
          streturn[0]="image"; streturn[1]= jtxtImage.getText();
          return streturn;
      }
      return null;
    }
    
    private void jBtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBrowseActionPerformed
        
        selectfile = new JFileChooser();
        
        // filtering selection of files only jpg and gif image files 
        filetype = new FileNameExtensionFilter("image files", "jpg", "gif");
        selectfile.addChoosableFileFilter(filetype);
        
        int response = selectfile.showOpenDialog(this);
        
        if (response == JFileChooser.APPROVE_OPTION) {
            File myfile = selectfile.getSelectedFile();
            jtxtImage.setText(myfile.getPath());
        }
    }//GEN-LAST:event_jBtnBrowseActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
        jtxtText.setEnabled(false);
        jtxtImage.setEnabled(false);
        jBtnBrowse.setEnabled(false);
        int selected_index = jComboBox.getSelectedIndex();
    
        if(selected_index == 1)
        {
            jtxtText.setEnabled(true);
        }
        if(selected_index == 2)
        {
            jtxtImage.setEnabled(true);
            jBtnBrowse.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBrowse;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtxtImage;
    private javax.swing.JTextField jtxtText;
    // End of variables declaration//GEN-END:variables
    private JFileChooser selectfile;
    private FileNameExtensionFilter filetype;
}
