/*
 * To change this template, choose Tools | Templates 
 * and open the template in the editor.
 */

/*
 * panel2.java
 *
 * Created on 9 Nov, 2012, 11:13:21 PM
 */
package GUIPackage;





/**
 *
 * @author User
 */
public class SelectAlgoPanel extends javax.swing.JPanel {

    public static final int a2_OUT_OF_2_2SUBPIXELS = 1;
    public static final int a2_OUT_OF_2_4SUBPIXELS = 2;
    public static final int RANDOM_GRID = 3;
    
    /** Creates new form panel2 */
    public SelectAlgoPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlblselectalgo = new javax.swing.JLabel();
        jRadioBtn2subpixels = new javax.swing.JRadioButton();
        jRadioBtn4subpixels = new javax.swing.JRadioButton();
        jRadioBtnRandomgrid = new javax.swing.JRadioButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlblselectalgo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblselectalgo.setText("SELECT ALGORITHM");
        add(jlblselectalgo);

        jRadioBtn2subpixels.setText("2 OUT OF 2(2 SUBPIXELS)");
        buttonGroup1.add(jRadioBtn2subpixels);
        jRadioBtn2subpixels.setSelected(true);
        jRadioBtn2subpixels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn2subpixelsActionPerformed(evt);
            }
        });
        add(jRadioBtn2subpixels);

        jRadioBtn4subpixels.setText("2 OUT OF 2(4 SUBPIXELS)");
        buttonGroup1.add(jRadioBtn4subpixels);
        jRadioBtn4subpixels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn4subpixelsActionPerformed(evt);
            }
        });
        add(jRadioBtn4subpixels);

        jRadioBtnRandomgrid.setText("RANDOM GRID");
        buttonGroup1.add(jRadioBtnRandomgrid);
        jRadioBtnRandomgrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnRandomgridActionPerformed(evt);
            }
        });
        add(jRadioBtnRandomgrid);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioBtn2subpixelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn2subpixelsActionPerformed
      selectedindex = a2_OUT_OF_2_2SUBPIXELS;
    }//GEN-LAST:event_jRadioBtn2subpixelsActionPerformed

    private void jRadioBtn4subpixelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn4subpixelsActionPerformed
        selectedindex = a2_OUT_OF_2_4SUBPIXELS;
    }//GEN-LAST:event_jRadioBtn4subpixelsActionPerformed

    private void jRadioBtnRandomgridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnRandomgridActionPerformed
        selectedindex = RANDOM_GRID;
    }//GEN-LAST:event_jRadioBtnRandomgridActionPerformed

    
    public int getAlgoSelection()
    {
       return selectedindex;
    }
    private int selectedindex=a2_OUT_OF_2_2SUBPIXELS;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioBtn2subpixels;
    private javax.swing.JRadioButton jRadioBtn4subpixels;
    private javax.swing.JRadioButton jRadioBtnRandomgrid;
    private javax.swing.JLabel jlblselectalgo;
    // End of variables declaration//GEN-END:variables
   
}
