/*
 * To change this template, choose Tools | Templates 
 * and open the template in the editor.
 */

/*
 * WatermarkingPanel.java
 *
 * Created on 15 Nov, 2012, 2:08:23 AM
 */
package GUIPackage;

import AlgoImplPackage.VCImageWaterMarking;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class WatermarkingPanel extends javax.swing.JPanel {

    /** Creates new form WatermarkingPanel */
    public WatermarkingPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtSecretkey = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtImage = new javax.swing.JTextField();
        jBtnBrowse = new javax.swing.JButton();
        jBtnVerfShare = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();

        jLabel1.setText("SECRET KEY");

        jtxtSecretkey.setColumns(7);

        jLabel2.setText("ENTER TEXT");

        jtxtText.setColumns(10);

        jLabel3.setText("HOST IMAGE");

        jtxtImage.setColumns(20);

        jBtnBrowse.setText("BROWSE");
        jBtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBrowseActionPerformed(evt);
            }
        });

        jBtnVerfShare.setText("CREATE VERIFICATION SHARE");
        jBtnVerfShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerfShareActionPerformed(evt);
            }
        });

        jbtnReset.setText("RESET");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSecretkey, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtxtImage, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(jBtnBrowse))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(jBtnVerfShare)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtSecretkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBtnBrowse))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVerfShare)
                    .addComponent(jbtnReset))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBrowseActionPerformed
        selectfile = new JFileChooser();
        
        filetype = new FileNameExtensionFilter("image files", "jpg", "gif");
        selectfile.addChoosableFileFilter(filetype);
        
        int response = selectfile.showOpenDialog(this);
        
        if (response == JFileChooser.APPROVE_OPTION) {
            myfile = selectfile.getSelectedFile();
            jtxtImage.setText(myfile.getPath());
        }   
    }//GEN-LAST:event_jBtnBrowseActionPerformed

    private void jBtnVerfShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerfShareActionPerformed
            
           int secretkey=0;
           File imagefile;
           textkey = jtxtSecretkey.getText();
           text = jtxtText.getText();
           imagepath = jtxtImage.getText();
           
           if(textkey.isEmpty() || text.isEmpty() || imagepath.isEmpty())
           {
               JOptionPane.showMessageDialog(this,"Fill in complete details");
           }
          else
           {   
              secretkey = Integer.parseInt(textkey);
             imagefile = new File(imagepath);
             
             vcimagewatermarking = new VCImageWaterMarking(secretkey, text, imagefile);
           } 
    }//GEN-LAST:event_jBtnVerfShareActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        
        jtxtText.setText("");
        jtxtSecretkey.setText("");
        jtxtImage.setText("");
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBrowse;
    private javax.swing.JButton jBtnVerfShare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxtImage;
    private javax.swing.JTextField jtxtSecretkey;
    private javax.swing.JTextField jtxtText;
    // End of variables declaration//GEN-END:variables
    private JFileChooser selectfile;
    private FileNameExtensionFilter filetype;
    private File myfile;
    private String imagepath;
    private String text=null;
    private String textkey;
    private VCImageWaterMarking vcimagewatermarking;
}
